/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'
import { Route as ClientesCarteiraRouteImport } from './routes/clientes.carteira'
import { Route as ClientesClienteIdIndexRouteImport } from './routes/clientes.$clienteId.index'
import { Route as ClientesClienteIdAcompanhamentoRouteImport } from './routes/clientes.$clienteId.acompanhamento'
import { Route as ClientesClienteIdCadastroRouteImport } from './routes/clientes.$clienteId.cadastro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesCarteiraRoute = ClientesCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesClienteIdIndexRoute = ClientesClienteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesClienteIdRoute,
} as any)
const ClientesClienteIdAcompanhamentoRoute =
  ClientesClienteIdAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => ClientesClienteIdRoute,
  } as any)
const ClientesClienteIdCadastroRoute =
  ClientesClienteIdCadastroRouteImport.update({
    id: '/cadastro',
    path: '/cadastro',
    getParentRoute: () => ClientesClienteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRouteWithChildren
  '/clientes/carteira': typeof ClientesCarteiraRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$clienteId/acompanhamento': typeof ClientesClienteIdAcompanhamentoRoute
  '/clientes/$clienteId/cadastro': typeof ClientesClienteIdCadastroRoute
  '/clientes/$clienteId/': typeof ClientesClienteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financeiro': typeof FinanceiroRoute
  '/clientes/carteira': typeof ClientesCarteiraRoute
  '/clientes': typeof ClientesIndexRoute
  '/clientes/$clienteId/acompanhamento': typeof ClientesClienteIdAcompanhamentoRoute
  '/clientes/$clienteId/cadastro': typeof ClientesClienteIdCadastroRoute
  '/clientes/$clienteId': typeof ClientesClienteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRouteWithChildren
  '/clientes/carteira': typeof ClientesCarteiraRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$clienteId/acompanhamento': typeof ClientesClienteIdAcompanhamentoRoute
  '/clientes/$clienteId/cadastro': typeof ClientesClienteIdCadastroRoute
  '/clientes/$clienteId/': typeof ClientesClienteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/financeiro'
    | '/clientes/$clienteId'
    | '/clientes/carteira'
    | '/clientes/'
    | '/clientes/$clienteId/acompanhamento'
    | '/clientes/$clienteId/cadastro'
    | '/clientes/$clienteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financeiro'
    | '/clientes/carteira'
    | '/clientes'
    | '/clientes/$clienteId/acompanhamento'
    | '/clientes/$clienteId/cadastro'
    | '/clientes/$clienteId'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/financeiro'
    | '/clientes/$clienteId'
    | '/clientes/carteira'
    | '/clientes/'
    | '/clientes/$clienteId/acompanhamento'
    | '/clientes/$clienteId/cadastro'
    | '/clientes/$clienteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/carteira': {
      id: '/clientes/carteira'
      path: '/carteira'
      fullPath: '/clientes/carteira'
      preLoaderRoute: typeof ClientesCarteiraRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$clienteId/': {
      id: '/clientes/$clienteId/'
      path: '/'
      fullPath: '/clientes/$clienteId/'
      preLoaderRoute: typeof ClientesClienteIdIndexRouteImport
      parentRoute: typeof ClientesClienteIdRoute
    }
    '/clientes/$clienteId/acompanhamento': {
      id: '/clientes/$clienteId/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/clientes/$clienteId/acompanhamento'
      preLoaderRoute: typeof ClientesClienteIdAcompanhamentoRouteImport
      parentRoute: typeof ClientesClienteIdRoute
    }
    '/clientes/$clienteId/cadastro': {
      id: '/clientes/$clienteId/cadastro'
      path: '/cadastro'
      fullPath: '/clientes/$clienteId/cadastro'
      preLoaderRoute: typeof ClientesClienteIdCadastroRouteImport
      parentRoute: typeof ClientesClienteIdRoute
    }
  }
}

interface ClientesClienteIdRouteChildren {
  ClientesClienteIdAcompanhamentoRoute: typeof ClientesClienteIdAcompanhamentoRoute
  ClientesClienteIdCadastroRoute: typeof ClientesClienteIdCadastroRoute
  ClientesClienteIdIndexRoute: typeof ClientesClienteIdIndexRoute
}

const ClientesClienteIdRouteChildren: ClientesClienteIdRouteChildren = {
  ClientesClienteIdAcompanhamentoRoute: ClientesClienteIdAcompanhamentoRoute,
  ClientesClienteIdCadastroRoute: ClientesClienteIdCadastroRoute,
  ClientesClienteIdIndexRoute: ClientesClienteIdIndexRoute,
}

const ClientesClienteIdRouteWithChildren =
  ClientesClienteIdRoute._addFileChildren(ClientesClienteIdRouteChildren)

interface ClientesRouteChildren {
  ClientesClienteIdRoute: typeof ClientesClienteIdRouteWithChildren
  ClientesCarteiraRoute: typeof ClientesCarteiraRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteIdRoute: ClientesClienteIdRouteWithChildren,
  ClientesCarteiraRoute: ClientesCarteiraRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
